config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home#index'
  #get '/', to: 'home#index', as: 'home'
  #get '/cards/:id', to: 'cards#show' =>mesmo codigo criado com resources(linha de codigo abaixo)
  #resources :cards, only: [:show, :index, :new, :create, :edit, :update]
  resources :cards do
    resources :comments, only:[:create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/card.rb
class Card < ApplicationRecord
  has_many :comments
  validates :front,  presence: true
  validates :author, presence: true
  validates :back, presence: true

  def descricao_amigavel
    "PT: #{front} => EN: #{back}"
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :card
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  before_action :set_card, only: [:show, :edit, :update, :destroy]

  def show
    @comment = Comment.new
  end

  def index
    @cards = Card.where(published:true)
  end

  def new
    @card = Card.new
  end

  def create
    @card = Card.new(card_parameters)
    if @card.save
      redirect_to @card
    else
      flash[:alert] = 'Por favor, preencher Portugues'
      render :new
    end
  end

  def edit
  end

  def update
    @card.update(card_parameters)
    redirect_to @card
  end

  def destroy
    @card.destroy
    redirect_to root_url
  end


  private
  def card_parameters
    params.require(:card).permit(:front, :back, :author)
  end

  def set_card
    @card = Card.find(params[:id])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    card = Card.find(params[:card_id])
    card.comments.create(params.require(:comment).permit(:author, :body))
    redirect_to card 
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @cards = Card.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/cards/edit.html.erb
<h1>Novo Card</h1>
<%= form_for(@card) do |f| %>
  <div>
    <%= f.label :front, "Portugues" %>
    <%= f.text_field :front %>
  </div>
  <div>
    <%= f.label :back, "Ingles" %>
    <%= f.text_field :back %>
  </div><br>
  <div>
    <%= f.label :author, "Autor" %>
    <%= f.text_field :author %>
  </div><br>

  <%= f.submit 'Atualizar' %>
<%end%>

app/views/cards/index.html.erb
<h2>Todos os cards</h2>

<% @cards.each do |card| %>
  <p><%= card.front %> -> <%= card.back %></p>
<%end%>

app/views/cards/new.html.erb
<p><%= flash[:alert] %></p>
<h1>Novo Card</h1>
<%= form_for(@card) do |f| %>
  <div>
    <%= f.label :front, "Portugues" %>
    <%= f.text_field :front %>
  </div>
  <div>
    <%= f.label :back, "Ingles" %>
    <%= f.text_field :back %>
  </div><br>
  <div>
    <%= f.label :author, "Autor" %>
    <%= f.text_field :author %>
  </div><br>
  <%= f.submit 'Enviar' %>
<%end%>

app/views/cards/show.html.erb
<header>
  <h2>Cards</h2><br>
</header>

<section>
  <h3>Expressao em portugues:</h3><%= @card.front %><br>
  <h3>Expressao em ingles:</h3><%= @card.back %>
  <p>Enviado por: <%= @card.author %></p>
  <p><%= link_to edit_card_path(@card) do %>
  <button>Editar</button>
  <%end%></p>

  <%= link_to @card, method: :delete do %>
  <button>Deletar</button><br>
  <% end %>

  <h3>Comentários</h3>
  <% @card.comments.each do |comment| %>
    <p><%= comment.author %> comentou:</p>
    <p><%= comment.body %></p>
    <% end %>

  <h2>Novo Comentario</h2>
  <%= form_for [@card, @comment] do |f| %>
    <div>
      <%= f.label :author, 'Autor' %>
      <%= f.text_field :author %>
    </div>
    <div>
      <%= f.label :body, 'Comentario' %>
      <%= f.text_area :body %>
    </div>
    <%= f.submit 'Enviar Comentario' %>
  <% end %>
</section>

app/views/home/index.html.erb
<section>
  <h2>Cards de traducao</h2>
</section>

<section>
  <p>Aplicacao criada para traduzir algumas expressoes</p><br>
</section>

<section>
  <h2>Cards Portugues/Ingles</h2>
  <% @cards.each do |card| %>
    <%= link_to card.front, card %><br><br>
  <% end %>
</section><br>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cards</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <%= link_to root_path do %>
      <h1>System cards</h1>
      <%= image_tag('tradutor.jpg', width: '300px', alt: "icone tradutor") %>
      <%end%>
    </header>
    <%= yield %>
    <section>
      <h3>Adicionar Novo Card</h3>
      <%= link_to new_card_path(@card) do %>
        <button> Novo </button>
      <% end %>
    </section>
    <aside>
      <h3>Outros tradutores</h3>
      <%= image_tag('google_tradutor_icon.png', width: '60px', alt: "icone google tradutor") %><br>
      <%= link_to "Google Tradutor", "http://translate.google.com", target: "_blank" %>
    </aside><br><br>

    <footer>
      <p><h5>Projeto Campus Code - firts app</h5></p>
  </body>
</html>